# Generated by Django 3.2 on 2023-06-08 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='IqTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('finish_time', models.DateTimeField()),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Create_test.createtest')),
            ],
        ),
        migrations.CreateModel(
            name='EqTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('finish_time', models.DateTimeField()),
                ('answer', models.CharField(max_length=5)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Create_test.createtest')),
            ],
        ),
    ]
